"""Initial migration

Revision ID: 077e7e6fd364
Revises: 
Create Date: 2026-05-15 12:57:22.877198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '077e7e6fd364'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONFIGURATION_LLM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name')
    )
    op.create_index(op.f('ix_CONFIGURATION_LLM_id'), 'CONFIGURATION_LLM', ['id'], unique=False)
    op.create_table('UTILISATEURS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UTILISATEURS_email'), 'UTILISATEURS', ['email'], unique=True)
    op.create_index(op.f('ix_UTILISATEURS_id'), 'UTILISATEURS', ['id'], unique=False)
    op.create_table('ANNONCES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UTILISATEURS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ANNONCES_id'), 'ANNONCES', ['id'], unique=False)
    op.create_table('CLIENTS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('subscription_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UTILISATEURS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_CLIENTS_id'), 'CLIENTS', ['id'], unique=False)
    op.create_table('IA_CONVERSATIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UTILISATEURS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IA_CONVERSATIONS_id'), 'IA_CONVERSATIONS', ['id'], unique=False)
    op.create_table('LOGS_SYSTEM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UTILISATEURS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LOGS_SYSTEM_id'), 'LOGS_SYSTEM', ['id'], unique=False)
    op.create_table('RECLAMATIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UTILISATEURS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RECLAMATIONS_id'), 'RECLAMATIONS', ['id'], unique=False)
    op.create_table('IA_MESSAGES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['IA_CONVERSATIONS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IA_MESSAGES_id'), 'IA_MESSAGES', ['id'], unique=False)
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('utilisateurs_pkey'))
    )
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.drop_index(op.f('ix_IA_MESSAGES_id'), table_name='IA_MESSAGES')
    op.drop_table('IA_MESSAGES')
    op.drop_index(op.f('ix_RECLAMATIONS_id'), table_name='RECLAMATIONS')
    op.drop_table('RECLAMATIONS')
    op.drop_index(op.f('ix_LOGS_SYSTEM_id'), table_name='LOGS_SYSTEM')
    op.drop_table('LOGS_SYSTEM')
    op.drop_index(op.f('ix_IA_CONVERSATIONS_id'), table_name='IA_CONVERSATIONS')
    op.drop_table('IA_CONVERSATIONS')
    op.drop_index(op.f('ix_CLIENTS_id'), table_name='CLIENTS')
    op.drop_table('CLIENTS')
    op.drop_index(op.f('ix_ANNONCES_id'), table_name='ANNONCES')
    op.drop_table('ANNONCES')
    op.drop_index(op.f('ix_UTILISATEURS_id'), table_name='UTILISATEURS')
    op.drop_index(op.f('ix_UTILISATEURS_email'), table_name='UTILISATEURS')
    op.drop_table('UTILISATEURS')
    op.drop_index(op.f('ix_CONFIGURATION_LLM_id'), table_name='CONFIGURATION_LLM')
    op.drop_table('CONFIGURATION_LLM')
    # ### end Alembic commands ###
