"""add_admin_response_to_claims

Revision ID: 321ea0b81abb
Revises: db2ea995564e
Create Date: 2026-06-15 10:58:33.947800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321ea0b81abb'
down_revision: Union[str, Sequence[str], None] = 'db2ea995564e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECLAMATIONS', sa.Column('admin_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECLAMATIONS', 'admin_response')
    # ### end Alembic commands ###
