"""link_claim_to_announcement

Revision ID: 82966f03bcf4
Revises: af4eabee2809
Create Date: 2026-06-16 11:54:52.039138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82966f03bcf4'
down_revision: Union[str, Sequence[str], None] = 'af4eabee2809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECLAMATIONS', sa.Column('announcement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'RECLAMATIONS', 'ANNONCES', ['announcement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RECLAMATIONS', type_='foreignkey')
    op.drop_column('RECLAMATIONS', 'announcement_id')
    # ### end Alembic commands ###
