"""Add password reset table

Revision ID: 9bd652b7d60f
Revises: 077e7e6fd364
Create Date: 2026-05-15 15:52:57.143300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd652b7d60f'
down_revision: Union[str, Sequence[str], None] = '077e7e6fd364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PASSWORD_RESETS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PASSWORD_RESETS_id'), 'PASSWORD_RESETS', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PASSWORD_RESETS_id'), table_name='PASSWORD_RESETS')
    op.drop_table('PASSWORD_RESETS')
    # ### end Alembic commands ###
