"""add client budget column

Revision ID: a59b6bfbbb13
Revises: 9bd652b7d60f
Create Date: 2026-06-13 22:47:03.162448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59b6bfbbb13'
down_revision: Union[str, Sequence[str], None] = '9bd652b7d60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CLIENTS', sa.Column('budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CLIENTS', 'budget')
    # ### end Alembic commands ###
