"""add_support_to_announcements

Revision ID: af4eabee2809
Revises: 321ea0b81abb
Create Date: 2026-06-15 22:49:25.700075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4eabee2809'
down_revision: Union[str, Sequence[str], None] = '321ea0b81abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ANNONCES', sa.Column('support', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ANNONCES', 'support')
    # ### end Alembic commands ###
