"""add budget and type columns to announcements

Revision ID: db2ea995564e
Revises: a59b6bfbbb13
Create Date: 2026-06-13 23:11:51.694500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2ea995564e'
down_revision: Union[str, Sequence[str], None] = 'a59b6bfbbb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ANNONCES', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('ANNONCES', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ANNONCES', 'type')
    op.drop_column('ANNONCES', 'budget')
    # ### end Alembic commands ###
